In [41]:
import pandas as pd
import numpy as np

In [42]:
#3 sigma comparisons
def flag_3sigma(df, checks):
    """
    checks: list of (value_col, sigma_col) tuples to test
    Adds a FITFLAG column: True if any field deviates > 3 sigma
    """

    flag = pd.Series(False, index=df.index)

    for val_col, sig_col in checks:
        if val_col in df.columns and sig_col in df.columns:
            residual = np.abs(df[val_col] - df[f"{val_col}_input"]) / df[sig_col]
            flag |= (residual > 3)

    df["FITFLAG"] = flag.astype(int)
    return df

In [43]:
data_dir = '~/Desktop/Data/final_runs/output/'

input_names = [
        "starid", "numax", "numax_err", "dnu", "dnu_err", "Teff", "Teff_err", "FeH", "FeH_err", "RA", "DEC", 
        "G_GAIA", "G_GAIA_err", "Mj_2MASS", "Mj_2MASS_err", "Mh_2MASS", "Mh_2MASS_err", "Mk_2MASS", "Mk_2MASS_err", "phase"
    ]

In [25]:
#Table 1: numax only input
table1 = []
for letter in ['a','b','c','d']:
    input_file = pd.read_csv(f'../data/basta_ascii_files/raw_{letter}.csv',sep='\s+',names=input_names)

    output_file = pd.read_csv(data_dir+f'table1_{letter}/results.ascii',sep='\s+')
    output_names = output_file.columns[1:]
    output_file = pd.read_csv(data_dir+f'table1_{letter}/results.ascii',sep='\s+',names=output_names,skiprows=1)

    output_file = output_file.merge(input_file,how='left',on='starid',suffixes=['','_input'])

    table1.append(output_file)
table1 = pd.concat(table1)

In [44]:
letter = 'a'
input_file = pd.read_csv(f'../data/basta_ascii_files/raw_{letter}.csv',sep='\s+',names=input_names)
output_file = pd.read_csv(data_dir+f'table1_{letter}/results.ascii',sep='\s+')
output_names = output_file.columns[1:]
output_file = pd.read_csv(data_dir+f'table1_{letter}/results.ascii',sep='\s+',names=output_names,skiprows=1)

output_df = output_file.merge(input_file,how='left',on='starid',suffixes=['','_input'])

In [39]:
input_file[input_file.duplicated(subset='starid',keep=False)].sort_values(by='starid')

,starid,numax,numax_err,dnu,dnu_err,Teff,Teff_err,FeH,FeH_err,RA,DEC,G_GAIA,G_GAIA_err,Mj_2MASS,Mj_2MASS_err,Mh_2MASS,Mh_2MASS_err,Mk_2MASS,Mk_2MASS_err,phase
1,2051366682266279424,33.95322,0.86678,4.12243,0.02954,4628.0,116.0,-0.4,0.20,289.927063,38.283967,13.718153,0.1,11.949,0.023,11.336,0.019,11.259,0.020,rgb
1808,2051366682266279424,34.31816,1.62716,4.05760,0.17446,4628.0,116.0,-0.4,0.20,289.927063,38.283967,13.718153,0.1,11.949,0.023,11.336,0.019,11.259,0.020,rgb
5,2052070434137218176,16.19818,0.85608,2.33180,0.06536,4750.0,100.0,0.5,0.20,294.144221,38.300231,12.382348,0.1,10.387,0.021,9.732,0.019,9.597,0.018,rgb
1812,2052070434137218176,15.98745,0.86767,2.29182,0.01582,4750.0,100.0,0.5,0.20,294.144221,38.300231,12.382348,0.1,10.387,0.021,9.732,0.019,9.597,0.018,rgb
28,2076180907362912896,14.05779,0.90331,1.83047,0.02710,4490.0,100.0,0.3,0.20,295.236838,39.083457,11.361166,0.1,9.327,0.021,8.670,0.018,8.464,0.017,rgb
1824,2076180907362912896,14.04205,0.63553,1.84952,0.01837,4490.0,100.0,0.3,0.20,295.236838,39.083457,11.361166,0.1,9.327,0.021,8.670,0.018,8.464,0.017,rgb
31,2076297593037446528,62.08726,2.72635,6.32485,0.04233,4466.0,130.0,-0.1,0.23,295.262692,40.079527,16.003075,0.1,14.102,0.028,13.515,0.028,13.382,0.041,rgb
1825,2076297593037446528,63.29983,1.50716,6.32549,0.02940,4466.0,130.0,-0.1,0.23,295.262692,40.079527,16.003075,0.1,14.102,0.028,13.515,0.028,13.382,0.041,rgb
32,2076323294119016576,34.52846,1.92417,3.87862,0.02241,4511.0,113.0,-0.0,0.20,295.709469,39.815454,14.234289,0.1,12.266,0.025,11.609,0.022,11.462,0.017,rgb
1826,2076323294119016576,33.89404,1.79344,3.88063,0.01755,4511.0,113.0,-0.0,0.20,295.709469,39.815454,14.234289,0.1,12.266,0.025,11.609,0.022,11.462,0.017,rgb
49,2078283311028205568,14.55975,1.14302,1.71688,0.01779,4528.0,106.0,0.0,0.20,294.795476,43.849737,11.526411,0.1,9.626,0.019,9.016,0.017,8.844,0.012,rgb
1833,2078283311028205568,13.60112,0.62458,1.73035,0.01732,4528.0,106.0,0.0,0.20,294.795476,43.849737,11.526411,0.1,9.626,0.019,9.016,0.017,8.844,0.012,rgb

In [45]:
output_file[output_file.duplicated(subset='starid',keep=False)].sort_values(by='starid')

,starid,distance,distance_errp,distance_errm,Teff,Teff_errp,Teff_errm,FeH,FeH_errp,FeH_errm,...,logg_errm,radPhot,radPhot_errp,radPhot_errm,massfin,massfin_errp,massfin_errm,age,age_errp,age_errm
1,2051366682266279424,3191.912847,79.056462,68.177268,4697.753905,27.925705,32.877349,-0.291738,0.131329,0.014019,...,0.010922,9.331097,0.574799,0.356626,0.859384,0.104763,0.058334,14900.0,3400.0,4900.0
1808,2051366682266279424,3190.026967,86.491089,75.372015,4698.437436,28.851492,39.641684,-0.291309,0.146687,0.014768,...,0.019616,9.324107,0.628292,0.399795,0.861734,0.107732,0.058768,14800.0,3400.0,4900.0
5,2052070434137218176,2216.183192,147.122476,143.589073,4531.664921,87.159549,93.353352,-0.055707,0.226135,0.172366,...,0.023632,16.634005,8.622788,2.797521,1.257356,1.769268,0.361463,4300.0,9700.0,3920.0
1812,2052070434137218176,2235.012349,148.343786,145.222604,4530.930354,87.707625,93.444901,-0.056083,0.226510,0.173427,...,0.024338,16.750461,8.815078,2.820235,1.261132,1.782032,0.363405,4300.0,9500.0,3940.0
28,2076180907362912896,1418.721237,54.422910,48.287837,4377.108108,83.180073,77.404535,-0.030342,0.208749,0.109375,...,0.029110,15.743341,1.528668,1.029242,0.983962,0.178793,0.109705,11600.0,5300.0,4800.0
1824,2076180907362912896,1420.844756,53.718767,46.588699,4377.108108,83.756133,77.611889,-0.030551,0.208957,0.109436,...,0.020399,15.776566,1.451282,0.985007,0.985155,0.177776,0.110909,11600.0,5300.0,4800.0
31,2076297593037446528,6500.493823,189.983724,162.172959,4610.012010,98.475899,58.944698,0.099827,0.081631,0.131599,...,0.021281,7.445540,1.334321,0.405145,0.955880,0.434856,0.078693,14600.0,4500.0,10800.0
1825,2076297593037446528,6395.529492,214.486655,160.534250,4640.012772,77.299547,81.615771,0.099834,0.216741,0.134518,...,0.011382,7.447552,1.344632,0.504322,1.017195,0.407115,0.137642,11100.0,7800.0,7600.0
32,2076323294119016576,3575.319129,101.633078,93.277323,4569.176320,95.999708,85.582136,-0.030109,0.202491,0.113899,...,0.025559,9.719475,1.062320,0.504933,0.922714,0.169851,0.068542,14600.0,3800.0,6800.0
1826,2076323294119016576,3603.965786,101.168199,92.260525,4565.663189,99.232591,84.947767,-0.030318,0.202548,0.117107,...,0.024529,9.797829,0.992817,0.496768,0.920998,0.162862,0.067097,14600.0,3800.0,6500.0
49,2078283311028205568,1657.914039,61.373670,54.120080,4481.910559,64.990841,83.550267,-0.154269,0.121287,0.148495,...,0.035873,14.974898,1.366236,0.964528,0.922113,0.155828,0.086983,12500.0,4700.0,5100.0
1833,2078283311028205568,1705.086931,61.013996,50.139547,4477.172511,58.379554,85.464460,-0.215776,0.181095,0.090969,...,0.020850,15.468929,1.334171,0.879751,0.922584,0.161937,0.089237,12300.0,4700.0,5100.0

In [ ]:

input = pd.read_csv('../data/basta_ascii_files/raw_a.csv',sep='\s+',names=input_names)

print(f"{output['Teff'].isna().sum()} stars where fitting failed :/")

checks = [
    ("FeH", "FeH_err"),
    ("Teff",  "Teff_err"),
    ("numax", "numax_err")
]

table1 = output.merge(input,how='left',on='starid',suffixes=['','_input'])

In [22]:
input

,starid,numax,numax_err,dnu,dnu_err,Teff,Teff_err,FeH,FeH_err,RA,DEC,G_GAIA,G_GAIA_err,Mj_2MASS,Mj_2MASS_err,Mh_2MASS,Mh_2MASS_err,Mk_2MASS,Mk_2MASS_err,phase
0,2051293702180102144,81.37265,1.37111,7.69527,0.08893,4630.0,106.0,-0.30,0.20,290.230496,37.816395,13.628399,0.1,11.922,0.021,11.346,0.020,11.250,0.017,rgb
1,2051366682266279424,33.95322,0.86678,4.12243,0.02954,4628.0,116.0,-0.40,0.20,289.927063,38.283967,13.718153,0.1,11.949,0.023,11.336,0.019,11.259,0.020,rgb
2,2051798167564062592,32.63989,1.36965,3.92382,0.03744,4844.0,134.0,0.09,0.24,291.698856,37.562533,13.757091,0.1,11.955,0.023,11.365,0.022,11.242,0.021,clump
3,2051829336143170816,34.99829,1.39113,4.04383,0.03599,4513.0,111.0,-0.20,0.21,292.694380,37.712675,14.149821,0.1,12.316,0.021,11.698,0.021,11.579,0.020,rgb
4,2052067002458806528,10.61619,0.41016,1.64400,0.01661,4337.0,107.0,-0.00,0.20,294.080439,38.133931,12.997641,0.1,10.839,0.021,10.142,0.022,9.952,0.018,rgb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1842,2101915870357239680,130.63957,4.85117,11.62737,0.31830,4634.0,135.0,-0.69,0.25,290.966676,41.928620,15.683603,0.1,14.127,0.042,13.583,0.046,13.516,0.051,rgb
1843,2103005486379630208,162.45882,3.46703,13.11274,0.03995,4833.0,129.0,-0.68,0.24,288.092232,43.466679,14.733486,0.1,13.303,0.044,12.746,0.045,12.715,0.039,rgb
1844,2126208205383797632,19.12865,0.95348,2.63403,0.02192,4499.0,111.0,-0.10,0.20,291.120792,44.285128,13.754391,0.1,11.800,0.021,11.182,0.021,11.005,0.014,rgb
1845,2131992353798606208,15.57669,0.82501,2.14227,0.01828,4500.0,100.0,-0.10,0.20,285.060160,49.144449,11.209722,0.1,9.447,0.022,8.816,0.016,8.677,0.019,rgb
1846,2134943344229709312,22.85507,1.00063,3.00141,0.01810,4553.0,129.0,-0.22,0.24,295.181459,49.838250,13.073682,0.1,11.290,0.021,10.697,0.017,10.563,0.017,rgb