In [1]:
import pandas as pd
import numpy as np

In [2]:
#3 sigma comparisons
def flag_3sigma(df, checks):
    """
    checks: list of (value_col, sigma_col) tuples to test
    Adds a FITFLAG column: True if any field deviates > 3 sigma
    """

    flag = pd.Series(False, index=df.index)

    for val_col, sig_col in checks:
        if val_col in df.columns and sig_col in df.columns:
            residual = np.abs(df[val_col] - df[f"{val_col}_input"]) / df[sig_col]
            flag |= (residual > 3)

    df["FITFLAG"] = flag.astype(int)
    return df

In [6]:
data_dir = '~/BASTA/BASTA/final_runs/output/'

input_names = [
        "starid", "numax", "numax_err", "dnu", "dnu_err", "Teff", "Teff_err", "FeH", "FeH_err", "RA", "DEC", 
        "G_GAIA", "G_GAIA_err", "Mj_2MASS", "Mj_2MASS_err", "Mh_2MASS", "Mh_2MASS_err", "Mk_2MASS", "Mk_2MASS_err", "phase"
    ]

In [15]:
#Table 1: numax only input
table1 = []
for letter in ['a','b','c','d']:
    input_file = pd.read_csv(f'../data/basta_ascii_files/raw_{letter}.ascii',sep='\s+',names=input_names)
    output_file = pd.read_csv(data_dir+f'table1_{letter}/results_clean.ascii',sep='\s+')

    output_df = output_file.merge(input_file,how='left',on='starid',suffixes=['','_input'])
    table1.append(output_df)
table1 = pd.concat(table1)

In [21]:
table1[table1.duplicated(subset='starid',keep=False)]

,starid,distance,distance_errp,distance_errm,Teff,Teff_errp,Teff_errm,FeH,FeH_errp,FeH_errm,...,DEC,G_GAIA,G_GAIA_err,Mj_2MASS,Mj_2MASS_err,Mh_2MASS,Mh_2MASS_err,Mk_2MASS,Mk_2MASS_err,phase
1807,2052585284746267904,3612.558009,158.724124,137.735918,4401.095129,83.475971,92.633539,-0.224058,0.187393,0.114797,...,38.231834,12.846096,0.1,10.884,0.024,10.209,0.023,10.04,0.02,rgb
6,2052585284746267904,3546.243958,126.484353,116.424050,4420.640995,89.348730,102.115120,-0.073777,0.147753,0.213623,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
true_sources = pd.read_csv('../data/true_sources_final.csv')

In [18]:
true_sources

,fname,source_id,numax,numax_sig,dnu,dnu_sig,certainty,syd_success,KIC,GaiaDR3,...,dec,phot_g_mean_mag,phot_g_mean_flux,phot_g_mean_flux_error,parallax,parallax_error,abs_mag,abs_mag_error,verifiable,rg
0,kic-000892641,2050232226787086976,33.35831,1.67907,4.08054,0.07095,2.0,1.0,NaN,NaN,...,36.621292,13.188555,99890.668270,12.850222,0.313083,0.009629,0.279305,0.088539,NaN,NaN
1,kic-000893398,2050237380747978368,33.27480,2.04071,4.11240,0.06994,2.0,1.0,NaN,NaN,...,36.637321,14.307139,35652.595385,5.820469,0.183497,0.014222,0.383066,0.172180,NaN,NaN
2,kic-000893295,2050237415107697152,29.98062,2.14249,4.19052,0.05754,2.0,1.0,NaN,NaN,...,36.633009,15.029545,18328.583443,3.803948,0.126498,0.019493,0.297755,0.336581,NaN,NaN
3,kic-001161372,2050249337936878336,26.87224,2.02758,4.10588,0.22120,2.0,1.0,NaN,NaN,...,36.809144,14.946826,19779.546817,4.308589,0.137907,0.018687,0.208769,0.301418,NaN,NaN
4,kic-001161477,2050256175524879616,23.15009,0.80148,3.44743,0.08424,2.0,1.0,NaN,NaN,...,36.878772,14.722102,24327.962526,4.932836,0.140459,0.017255,0.023863,0.274666,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2576,kic-012647359,2139224876865175168,28.92967,2.49656,3.97476,0.08131,2.0,1.0,NaN,NaN,...,51.700677,14.183556,39950.708141,7.732766,0.194564,0.012922,0.313984,0.151758,NaN,NaN
2577,kic-012784560,2139295657926520832,32.79546,1.48246,3.96463,0.02011,2.0,2.0,NaN,NaN,...,52.046496,15.569255,11149.223975,3.580595,0.053287,0.023483,-1.015650,0.957493,NaN,NaN
2578,kic-012735587,2139299506217117568,34.25882,1.73330,4.18787,0.17950,2.0,1.0,NaN,NaN,...,51.966917,14.186991,39824.512942,5.991647,0.186387,0.014164,0.296854,0.168967,NaN,NaN
2579,kic-012934949,2139323764192611584,27.31982,1.02138,3.71400,0.05058,2.0,1.0,NaN,NaN,...,52.354949,14.191562,39657.208581,6.300113,0.185872,0.012676,0.271196,0.153387,NaN,NaN
2580,kic-010843934,2143714904395223168,41.05510,4.99136,4.89245,0.09001,2.0,1.0,NaN,NaN,...,48.254408,16.806278,3568.085208,2.172035,0.011553,0.045025,0.988052,0.776215,NaN,NaN

In [30]:
letter = 'b'
input_file = pd.read_csv(f'../data/basta_ascii_files/raw_{letter}.ascii',sep='\s+',names=input_names)
output_file = pd.read_csv(data_dir+f'table1_{letter}/results_clean.ascii',sep='\s+')

output_df = output_file.merge(input_file,how='left',on='starid',suffixes=['','_input'])

In [40]:
len(input_file)

625

In [32]:
len(output_file)

626

In [39]:
len(output_df)

626

In [39]:
input_file[input_file.duplicated(subset='starid',keep=False)].sort_values(by='starid')

,starid,numax,numax_err,dnu,dnu_err,Teff,Teff_err,FeH,FeH_err,RA,DEC,G_GAIA,G_GAIA_err,Mj_2MASS,Mj_2MASS_err,Mh_2MASS,Mh_2MASS_err,Mk_2MASS,Mk_2MASS_err,phase
1,2051366682266279424,33.95322,0.86678,4.12243,0.02954,4628.0,116.0,-0.4,0.20,289.927063,38.283967,13.718153,0.1,11.949,0.023,11.336,0.019,11.259,0.020,rgb
1808,2051366682266279424,34.31816,1.62716,4.05760,0.17446,4628.0,116.0,-0.4,0.20,289.927063,38.283967,13.718153,0.1,11.949,0.023,11.336,0.019,11.259,0.020,rgb
5,2052070434137218176,16.19818,0.85608,2.33180,0.06536,4750.0,100.0,0.5,0.20,294.144221,38.300231,12.382348,0.1,10.387,0.021,9.732,0.019,9.597,0.018,rgb
1812,2052070434137218176,15.98745,0.86767,2.29182,0.01582,4750.0,100.0,0.5,0.20,294.144221,38.300231,12.382348,0.1,10.387,0.021,9.732,0.019,9.597,0.018,rgb
28,2076180907362912896,14.05779,0.90331,1.83047,0.02710,4490.0,100.0,0.3,0.20,295.236838,39.083457,11.361166,0.1,9.327,0.021,8.670,0.018,8.464,0.017,rgb
1824,2076180907362912896,14.04205,0.63553,1.84952,0.01837,4490.0,100.0,0.3,0.20,295.236838,39.083457,11.361166,0.1,9.327,0.021,8.670,0.018,8.464,0.017,rgb
31,2076297593037446528,62.08726,2.72635,6.32485,0.04233,4466.0,130.0,-0.1,0.23,295.262692,40.079527,16.003075,0.1,14.102,0.028,13.515,0.028,13.382,0.041,rgb
1825,2076297593037446528,63.29983,1.50716,6.32549,0.02940,4466.0,130.0,-0.1,0.23,295.262692,40.079527,16.003075,0.1,14.102,0.028,13.515,0.028,13.382,0.041,rgb
32,2076323294119016576,34.52846,1.92417,3.87862,0.02241,4511.0,113.0,-0.0,0.20,295.709469,39.815454,14.234289,0.1,12.266,0.025,11.609,0.022,11.462,0.017,rgb
1826,2076323294119016576,33.89404,1.79344,3.88063,0.01755,4511.0,113.0,-0.0,0.20,295.709469,39.815454,14.234289,0.1,12.266,0.025,11.609,0.022,11.462,0.017,rgb
49,2078283311028205568,14.55975,1.14302,1.71688,0.01779,4528.0,106.0,0.0,0.20,294.795476,43.849737,11.526411,0.1,9.626,0.019,9.016,0.017,8.844,0.012,rgb
1833,2078283311028205568,13.60112,0.62458,1.73035,0.01732,4528.0,106.0,0.0,0.20,294.795476,43.849737,11.526411,0.1,9.626,0.019,9.016,0.017,8.844,0.012,rgb

In [45]:
output_file[output_file.duplicated(subset='starid',keep=False)].sort_values(by='starid')

,starid,distance,distance_errp,distance_errm,Teff,Teff_errp,Teff_errm,FeH,FeH_errp,FeH_errm,...,logg_errm,radPhot,radPhot_errp,radPhot_errm,massfin,massfin_errp,massfin_errm,age,age_errp,age_errm
1,2051366682266279424,3191.912847,79.056462,68.177268,4697.753905,27.925705,32.877349,-0.291738,0.131329,0.014019,...,0.010922,9.331097,0.574799,0.356626,0.859384,0.104763,0.058334,14900.0,3400.0,4900.0
1808,2051366682266279424,3190.026967,86.491089,75.372015,4698.437436,28.851492,39.641684,-0.291309,0.146687,0.014768,...,0.019616,9.324107,0.628292,0.399795,0.861734,0.107732,0.058768,14800.0,3400.0,4900.0
5,2052070434137218176,2216.183192,147.122476,143.589073,4531.664921,87.159549,93.353352,-0.055707,0.226135,0.172366,...,0.023632,16.634005,8.622788,2.797521,1.257356,1.769268,0.361463,4300.0,9700.0,3920.0
1812,2052070434137218176,2235.012349,148.343786,145.222604,4530.930354,87.707625,93.444901,-0.056083,0.226510,0.173427,...,0.024338,16.750461,8.815078,2.820235,1.261132,1.782032,0.363405,4300.0,9500.0,3940.0
28,2076180907362912896,1418.721237,54.422910,48.287837,4377.108108,83.180073,77.404535,-0.030342,0.208749,0.109375,...,0.029110,15.743341,1.528668,1.029242,0.983962,0.178793,0.109705,11600.0,5300.0,4800.0
1824,2076180907362912896,1420.844756,53.718767,46.588699,4377.108108,83.756133,77.611889,-0.030551,0.208957,0.109436,...,0.020399,15.776566,1.451282,0.985007,0.985155,0.177776,0.110909,11600.0,5300.0,4800.0
31,2076297593037446528,6500.493823,189.983724,162.172959,4610.012010,98.475899,58.944698,0.099827,0.081631,0.131599,...,0.021281,7.445540,1.334321,0.405145,0.955880,0.434856,0.078693,14600.0,4500.0,10800.0
1825,2076297593037446528,6395.529492,214.486655,160.534250,4640.012772,77.299547,81.615771,0.099834,0.216741,0.134518,...,0.011382,7.447552,1.344632,0.504322,1.017195,0.407115,0.137642,11100.0,7800.0,7600.0
32,2076323294119016576,3575.319129,101.633078,93.277323,4569.176320,95.999708,85.582136,-0.030109,0.202491,0.113899,...,0.025559,9.719475,1.062320,0.504933,0.922714,0.169851,0.068542,14600.0,3800.0,6800.0
1826,2076323294119016576,3603.965786,101.168199,92.260525,4565.663189,99.232591,84.947767,-0.030318,0.202548,0.117107,...,0.024529,9.797829,0.992817,0.496768,0.920998,0.162862,0.067097,14600.0,3800.0,6500.0
49,2078283311028205568,1657.914039,61.373670,54.120080,4481.910559,64.990841,83.550267,-0.154269,0.121287,0.148495,...,0.035873,14.974898,1.366236,0.964528,0.922113,0.155828,0.086983,12500.0,4700.0,5100.0
1833,2078283311028205568,1705.086931,61.013996,50.139547,4477.172511,58.379554,85.464460,-0.215776,0.181095,0.090969,...,0.020850,15.468929,1.334171,0.879751,0.922584,0.161937,0.089237,12300.0,4700.0,5100.0

In [11]:
output_file

,starid,distance,distance_errp,distance_errm,Teff,Teff_errp,Teff_errm,FeH,FeH_errp,FeH_errm,...,logg_errm,radPhot,radPhot_errp,radPhot_errm,massfin,massfin_errp,massfin_errm,age,age_errp,age_errm
0,2051293702180102144,2131.320792,51.886245,48.802704,4775.520426,86.319048,72.957692,-0.041427,0.140593,0.185268,...,0.008306,6.404904,1.130865,0.267249,0.980039,0.385315,0.075072,10700.0,3900.0,7000.0
1,2051366682266279424,3191.912847,79.056462,68.177268,4697.753905,27.925705,32.877349,-0.291738,0.131329,0.014019,...,0.010922,9.331097,0.574799,0.356626,0.859384,0.104763,0.058334,14900.0,3400.0,4900.0
2,2051798167564062592,3174.680980,102.329555,88.364031,4828.846929,108.358907,94.076426,0.067957,0.089257,0.256250,...,0.016761,8.990932,0.624268,0.446888,0.769461,0.113859,0.067629,14500.0,3700.0,4300.0
3,2051829336143170816,3645.960207,90.159177,80.334328,4633.118449,68.300812,81.169478,-0.134641,0.220836,0.156247,...,0.017536,9.414251,0.647321,0.406437,0.888463,0.119810,0.057992,15100.0,3400.0,5200.0
4,2052067002458806528,3200.644136,125.718573,94.898374,4337.749602,89.273682,85.389671,-0.036777,0.135831,0.182928,...,0.017674,17.890248,1.543192,1.001752,0.948774,0.164887,0.094808,12500.0,4900.0,5200.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1836,2101915870357239680,4706.384874,118.079639,108.838474,4920.375831,111.248796,94.622807,-0.290496,0.159392,0.164472,...,0.017308,4.745851,0.518415,0.196540,0.872503,0.209196,0.057006,14100.0,3500.0,6900.0
1837,2103005486379630208,2875.977284,65.742746,61.331031,5040.080877,89.717368,103.887786,-0.438420,0.209799,0.096032,...,0.010316,4.183687,0.572141,0.161656,0.855830,0.255988,0.060465,13400.0,3500.0,7700.0
1838,2126208205383797632,3917.360404,127.110994,106.151851,4513.298125,77.892875,74.888541,-0.137214,0.106881,0.157301,...,0.022654,12.929233,0.959226,0.648698,0.905083,0.133954,0.070364,13800.0,4000.0,5100.0
1839,2131992353798606208,1463.466707,45.955800,38.935850,4500.865733,57.933400,82.587697,-0.160216,0.126262,0.142274,...,0.024172,14.352699,1.142787,0.770282,0.908222,0.144663,0.077495,13100.0,4300.0,5100.0
1840,2134943344229709312,2869.049542,81.561497,69.420425,4603.794297,95.808807,100.829915,-0.223524,0.189769,0.112972,...,0.020437,11.650201,0.871951,0.563010,0.886493,0.132846,0.069162,13900.0,3800.0,5200.0

In [12]:
input_file

,starid,numax,numax_err,dnu,dnu_err,Teff,Teff_err,FeH,FeH_err,RA,DEC,G_GAIA,G_GAIA_err,Mj_2MASS,Mj_2MASS_err,Mh_2MASS,Mh_2MASS_err,Mk_2MASS,Mk_2MASS_err,phase
0,2050232226787086976,33.35831,1.67907,4.08054,0.07095,4719.0,117.0,0.10,0.20,291.121190,36.621292,13.188555,0.1,11.372,0.020,10.789,0.019,10.664,0.017,clump
1,2050237380747978368,33.27480,2.04071,4.11240,0.06994,4601.0,121.0,0.09,0.22,291.286741,36.637321,14.307139,0.1,12.573,0.021,11.991,0.022,11.878,0.021,clump
2,2050237415107697152,29.98062,2.14249,4.19052,0.05754,4918.0,166.0,-0.22,0.26,291.266349,36.633009,15.029545,0.1,13.394,0.046,12.877,0.051,12.823,0.050,clump
3,2050256175524879616,23.15009,0.80148,3.44743,0.08424,4707.0,121.0,0.20,0.20,291.077319,36.878772,14.722102,0.1,12.975,0.021,12.353,0.021,12.259,0.021,clump
4,2051083214425133568,31.34210,2.05195,3.78118,0.05116,4662.0,120.0,0.50,0.20,290.498641,37.449316,14.252887,0.1,12.379,0.027,11.805,0.031,11.624,0.026,clump
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1836,2135563120891529728,9.18327,0.55256,1.38879,0.01343,4428.0,107.0,0.40,0.20,295.524070,50.875565,12.004397,0.1,9.938,0.021,9.238,0.018,9.098,0.016,rgb
1837,2135571646404547584,74.31862,4.66692,7.25643,0.09339,4606.0,141.0,0.04,0.25,295.124200,50.852743,15.473360,0.1,13.757,0.025,13.133,0.017,13.085,0.033,rgb
1838,2139224876865175168,28.92967,2.49656,3.97476,0.08131,4671.0,121.0,0.10,0.21,290.623577,51.700677,14.183556,0.1,12.461,0.023,11.879,0.030,11.773,0.026,clump
1839,2139295657926520832,32.79546,1.48246,3.96463,0.02011,4627.0,139.0,-0.62,0.25,290.050309,52.046496,15.569255,0.1,13.894,0.034,13.353,0.036,13.249,0.035,rgb
1840,2139323764192611584,27.31982,1.02138,3.71400,0.05058,4726.0,136.0,-0.19,0.23,290.116373,52.354949,14.191562,0.1,12.518,0.040,11.961,0.040,11.840,0.029,clump

In [13]:
output_df

,starid,distance,distance_errp,distance_errm,Teff,Teff_errp,Teff_errm,FeH,FeH_errp,FeH_errm,...,DEC,G_GAIA,G_GAIA_err,Mj_2MASS,Mj_2MASS_err,Mh_2MASS,Mh_2MASS_err,Mk_2MASS,Mk_2MASS_err,phase
0,2051293702180102144,2131.320792,51.886245,48.802704,4775.520426,86.319048,72.957692,-0.041427,0.140593,0.185268,...,37.816395,13.628399,0.1,11.922,0.021,11.346,0.020,11.250,0.017,rgb
1,2051366682266279424,3191.912847,79.056462,68.177268,4697.753905,27.925705,32.877349,-0.291738,0.131329,0.014019,...,38.283967,13.718153,0.1,11.949,0.023,11.336,0.019,11.259,0.020,rgb
2,2051798167564062592,3174.680980,102.329555,88.364031,4828.846929,108.358907,94.076426,0.067957,0.089257,0.256250,...,37.562533,13.757091,0.1,11.955,0.023,11.365,0.022,11.242,0.021,clump
3,2051829336143170816,3645.960207,90.159177,80.334328,4633.118449,68.300812,81.169478,-0.134641,0.220836,0.156247,...,37.712675,14.149821,0.1,12.316,0.021,11.698,0.021,11.579,0.020,rgb
4,2052067002458806528,3200.644136,125.718573,94.898374,4337.749602,89.273682,85.389671,-0.036777,0.135831,0.182928,...,38.133931,12.997641,0.1,10.839,0.021,10.142,0.022,9.952,0.018,rgb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1836,2101915870357239680,4706.384874,118.079639,108.838474,4920.375831,111.248796,94.622807,-0.290496,0.159392,0.164472,...,41.928620,15.683603,0.1,14.127,0.042,13.583,0.046,13.516,0.051,rgb
1837,2103005486379630208,2875.977284,65.742746,61.331031,5040.080877,89.717368,103.887786,-0.438420,0.209799,0.096032,...,43.466679,14.733486,0.1,13.303,0.044,12.746,0.045,12.715,0.039,rgb
1838,2126208205383797632,3917.360404,127.110994,106.151851,4513.298125,77.892875,74.888541,-0.137214,0.106881,0.157301,...,44.285128,13.754391,0.1,11.800,0.021,11.182,0.021,11.005,0.014,rgb
1839,2131992353798606208,1463.466707,45.955800,38.935850,4500.865733,57.933400,82.587697,-0.160216,0.126262,0.142274,...,49.144449,11.209722,0.1,9.447,0.022,8.816,0.016,8.677,0.019,rgb
1840,2134943344229709312,2869.049542,81.561497,69.420425,4603.794297,95.808807,100.829915,-0.223524,0.189769,0.112972,...,49.838250,13.073682,0.1,11.290,0.021,10.697,0.017,10.563,0.017,rgb